package com.example.bookstore.dto;

public enum MessageCode {
    ERROR_MESSAGE,
    SUCCESS_MESSAGE,
    CONNECTION_TIMEOUT,
    FOREIGN_KEY_EXCEPTION,
    QUANTITY_LIMIT,
    NOT_FOUND,
    CART_EMPTY,
    CONNECTION_ERROR,
    SUCCESS_ORDER,
    ERROR_ORDER,
    POST_SUCCESS,
    CANCEL_SUCCESS_ORDER,
    INPUT_IMAGE_ERROR,
    INPUT_TITLE_ERROR,
    INPUT_AUTHOR_ERROR,
    INPUT_QUANTITY_ERROR,
    INPUT_PRICE_ERROR,
    INPUT_PUBLISHER_ERROR,
    INPUT_CATEGORY_ERROR,
    INPUT_DATESALE_ERROR;
}
